### ISSUE TITLE
this extension overrides other font-awsome icons i am using..

### ISSUE THREAD

**Issue by seatechdev** [AndreLGava/font-awesome-extension#3]
It overrides the other font-awsome icons e.g. fa-credit-card

my header for the index.html

link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet" integrity="integrity SHA Code here" crossorigin="anonymous"

link href="faextension/font-awesome-extension/styles.css" rel="stylesheet"

**Comment by AndreLZGava** [comment]
Wich icon had overide the fa-credit-card? Has it occured with other icons?

**Comment by seatechdev** [comment]
fa-wallet.  It overrides the entire tab bar for my  Cordova mobile app.  Thanks.

**Comment by AndreLZGava** [comment]
Hello, i've modified Font Awesome Extension, now instead you use fa-icon you should use fae-icon, this should fix your problem, so download the new version, if you have any other problem please tell me, do you need any other icon too?

**Comment by AndreLZGava** [comment]
Did this resolve your problem? If yes please tell me so then I'll close this issue. Thanks

**Comment by seatechdev** [comment]
I will be testing it this weekend.  Also is there an Icon for a vacation spot?  May be buildings and palm trees or globe with airplane.  Other suggestions - gift cards,  ID card, loyalty card

**Comment by seatechdev** [comment]
It works now.  However, there is a minor issue.  The icon is not aligned with other fa-icons.   All the icons are at 2x size.  If i increase it to 3x - it gets closer but slightly bigger than other 2x icons.  Is there a workaround?

![dashboardtabs](https://cloud.githubusercontent.com/assets/4111840/15418119/7804e2ca-1e11-11e6-9106-25b0d3358f86.PNG)

**Comment by AndreLZGava** [comment]
Great that this works now, I will try discover why this is happening, untill tomorrow I'll give you a feedback

**Comment by AndreLZGava** [comment]
This is because I have design icons a litle bit smaller than the original Font Awesome, I worked all day in the project soon I'll deliver another version

**Comment by seatechdev** [comment]
Thank you for all your hard work and help.  I look forward to seeing the new version.

**Comment by AndreLZGava** [comment]
I had commited new version of Font Awesome Extension, I hope that now this is great :D

**Comment by seatechdev** [comment]
It works.  It had a vertical alignment issue.  So I copied the following from the font-awesome css to address the issue:

vertical-align: -15%;

 Also, I realized that you didn't need to manually resize the icons.  Instead, adding something like
 font-size: 1.33333333em 
would have solved the problem.

Thank you for all your help.  Cheers!

**Comment by AndreLZGava** [comment]
Great, very happy about it, Yes it could revsolved the problem, but I wanted to post another version, have you used this new version or ther version of 42 icons(v0.0.2)?

**Comment by seatechdev** [comment]
New icons
