### ISSUE TITLE
License

### ISSUE THREAD

**Issue by yoavram** [AndreLGava/font-awesome-extension#6]
Great font collection.
Can you please add a license to the repo/README/website?

For example, I see this one in use: [OFL](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web)

**Comment by AndreLZGava** [comment]
Thanks for using Font Awesome Extension
And Thanks for create this issue.

If you have any other sugestion or doubt please create another issue.

**Comment by yoavram** [comment]
(closed by 09d80249058ee8018a45da30add4339289dbb466)
